### ISSUE TITLE
Convert to Moo?

### ISSUE THREAD

**Issue by frioux** [mindvessel/Feed-Pipe#1]
This module would load up a lot faster if it were written for Moo instead of Moose.  Would you accept pull requests to do that?

**Comment by veselosky** [comment]
Hi frioux,

I don't actually maintain or use this software anymore. I've left it available in case folks found it useful (as I once did). If you would like to take over maintenance of the package I'd be happy to add you as a committer or transfer ownership to you. Assuming I can manage to guess my old CPAN password! :)

If you're interested, just ping me back.

— Vince

**Comment by frioux** [comment]
Yep, I can take it from here. Thanks!

## 

sent from a rotary phone, pardon my brevity

**Comment by veselosky** [comment]
@frioux If I managed to press the buttons correctly, you should now have commit bit on this repo, as well as permission to upload this module to CPAN. If you don't have access, let me know, and I'll try to figure out what I did wrong! :)

**Comment by frioux** [comment]
Excellent, seems to have worked!  Check out the new release here, if you are interested: https://metacpan.org/pod/release/FREW/Feed-Pipe-1.004/lib/Feed/Pipe.pm

I forked your repo and made my fork the canonical one, as that seems the most legitimate thing to do when there isn't a github organization.
